name: echo

# Trigger
on:
  workflow_dispatch:
  push:
    branches:
      - main

# Action
jobs:
  echo:
    name: Echo a string
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "Look, I'm a string!"