name: Pytest Python Files

# Trigger
on:
  workflow_dispatch:
  push:
    paths:
      - '**.py'
    branches:
      - main

# Action
jobs:
  pytest:
    name: Pytest Python Code
    runs-on: ubuntu-latest
    steps:
      # Clone repository content
      - uses: actions/checkout@v6
      # Install Python
      - name: Install Python
        uses: actions/setup-python@v6
      # Install requirements
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Test the Code
        run: pytest test_main.py
